name: Build and push Docker image

on:
  push:
    branches:
      - master

env:
  TZ: Europe/Paris
  REGISTRY: ghcr.io
  IMAGE_NAME: georgestech/puppeteer-base-image

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Lint Dockerfile with Hadolint
        uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: Dockerfile
          failure-threshold: error

      - name: Image security check with Dockle
        uses: hands-lab/dockle-action@v1
        with:
          image: '${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest'
          exit-code: '1'
          exit-level: FATAL

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
